### ISSUE TITLE
[caom2-tap] Datatype is incorrect for Plane.polarization.dimension

### ISSUE THREAD

**Issue by at88mph** [opencadc/caom2service#20]
When loading a particular Plane into the `caom2ops/meta` service, some observations are throwing errors:

`
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at ca.nrc.cadc.caom2ops.Util.getLong(Util.java:86)
	at ca.nrc.cadc.caom2ops.mapper.PlaneMapper.mapRow(PlaneMapper.java:226)
	at ca.nrc.cadc.caom2ops.CaomTapQuery.buildObservation(CaomTapQuery.java:359)
	at ca.nrc.cadc.caom2ops.CaomTapQuery.performQuery(CaomTapQuery.java:165)
	at ca.nrc.cadc.caom2.meta.MetaQueryRunner.doIt(MetaQueryRunner.java:210)
	at ca.nrc.cadc.caom2.meta.MetaQueryRunner.run(MetaQueryRunner.java:159)
	at ca.nrc.cadc.uws.server.AbstractExecutor.executeSync(AbstractExecutor.java:208)
	at ca.nrc.cadc.uws.server.AbstractExecutor.execute(AbstractExecutor.java:171)
	at ca.nrc.cadc.uws.server.SimpleJobManager.execute(SimpleJobManager.java:220)
	at ca.nrc.cadc.uws.server.SyncServlet.processRequest(SyncServlet.java:410)
	at ca.nrc.cadc.uws.server.SyncServlet.access$000(SyncServlet.java:109)
	at ca.nrc.cadc.uws.server.SyncServlet$1.run(SyncServlet.java:298)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:421)
	at ca.nrc.cadc.uws.server.SyncServlet.doit(SyncServlet.java:293)
	at ca.nrc.cadc.uws.server.SyncServlet.doGet(SyncServlet.java:247)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:190)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
`

The `Util.getLong() method` is trying to cast a Long to an Integer.

Version 1.3.1 does not have this problem, and so was introduced in 1.3.2.

**Comment by brianmajor** [comment]
This was caused by an incorrect type in the TAP_SCHEMA for plarization.dimension.
